version: '3.8'


services:
  postgres-server:
    build:
      context: ./postgres-server
      dockerfile: Dockerfile
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5555:5678"
    command: -p 5678
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h postgres-server -p 5678 -d linkholder -U mikko" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app-server:
    build:
      context: ./app-server
      dockerfile: Dockerfile
    container_name: app-server
    environment:
      - POSTGRES_HOST=postgres-server
      - POSTGRES_PORT=5678
      - POSTGRES_USER=mikko
      - POSTGRES_PASSWORD=masterkey
      - DB_NAME=linkholder
    volumes:
      - ./app-server/static:/url-shorter/static
      - ./app-server/templates:/url-shorter/templates
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://0.0.0.0:5856/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres-server:
        condition: service_healthy

  nginx-server:
    build:
      context: ./nginx-server
      dockerfile: Dockerfile
    container_name: nginx-server
    volumes:
      - ./app-server/static:/url-shorter/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      app-server:
        condition: service_healthy
